### PR TITLE
Added data attribute to capture object, created an array to push this…

### PR DESCRIPTION
**Pull request by KeyboardCowboy008**
Added data attribute to our favorite button, pushed this attribute into an array, and then pushed that array into local storage so favorites are saved.

### CODE REVIEW

**Comment by mdub187** [comment]
dope

**Review by mdub187 — APPROVED** [review]
it looks good to me.

**Comment by HamzahAlsalmi** [comment]
looks good

**Review by HamzahAlsalmi — COMMENTED** [review]
nice job!

**Pull request merged**
